/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBear: typeof import('./components/AppBear.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Files: typeof import('./components/Files.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Login: typeof import('./components/Login.vue')['default']
    NavigationDrawer: typeof import('./components/NavigationDrawer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Shared: typeof import('./components/Shared.vue')['default']
    Starred: typeof import('./components/Starred.vue')['default']
    Started: typeof import('./components/Started.vue')['default']
  }
}
